name: airbnb_host_analytics

config-version: 2
version: 1.0.0

profile: dbt_bigquery

model-paths: ["models"]
test-paths: ["tests"]

models:
  airbnb_host_analytics:
    staging:
      materialized: table
    data_mart:
      materialized: table
    metric_layer:
      materialized: table