name: CICD pipeline
run-name: ${{ github.actor }} is conducting unit test & integration test 🚀
on: [push]
jobs:
  Conduct-Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository code
        run: |
          echo "Cloning repository..."
          git clone https://github.com/TravisH0301/airbnb_host_analytics.git .
          echo "Cloning completed."
      - name: Install dependencies
        run: |
          echo "Install dependencies..."
          pip install -r ./tests/requirements.txt
          echo "Installation completed."
      - name: Run test script - test_ingest_data.py
        run: |
          echo "Running first test script..."
          python -m unittest ./tests/test_ingest_data.py
          echo "Test completed."
      - name: Run test script - test_utils.py
        run: |
          echo "Running second test script..."
          python -m unittest ./tests/test_utils.py
          echo "Test completed."