name: CICD pipeline
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Conduct-Testing:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Cloning repository..."
      - name: Clone repository code
        uses: actions/checkout@v4
  
      - run: echo "Install dependencies..."
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - run: echo "Conducting first test script..."
      - name: Run test script - test_ingest_data.py
        run: python -m unitest /test/test_ingest_data.py